version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: churn_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: telco_churn
      MYSQL_USER: churn_user
      MYSQL_PASSWORD: churn_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "churn_user", "-pchurn_password"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: churn_fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://churn_user:churn_password@db:3306/telco_churn
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app/ml/saved_models:/workspace/app/ml/saved_models
      - .:/workspace

  prometheus:
    image: prom/prometheus:latest
    container_name: churn_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: churn_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

volumes:
  mysql_data:
